### ISSUE TITLE
predict_mask options with num results not working

### ISSUE THREAD

**Issue by LoganRoth** [EricFillion/happy-transformer#114]
When options are given and a num_results is specified only the first "num_results" of the options are being returned, even if those are not the highest scored options

**Comment by LoganRoth** [comment]
I believe the offending line is line 101 in happy_transformer.py: option_ids = option_ids[:num_results]

**Comment by EricFillion** [comment]
It seems to work for HappyBERT, but not HappyXLNET or HappyROBERTA. I'm looking into it now.
