### ISSUE TITLE
Inconsistent masked word prediction results

### ISSUE THREAD

**Issue by yuchenlin** [EricFillion/happy-transformer#120]
Hi!

Thanks very much for the great work! I found a trouble of ROBERTA's masked word prediction results are not the same as the official fairseq one.

You can test it by the example here: https://github.com/pytorch/fairseq/tree/master/examples/roberta#filling-masks

**Comment by yuchenlin** [comment]
It seems that the inconsistency is there also for BERT. 

You can compare the results between HappyTransformer and my own simple  implementation here:

https://gist.github.com/yuchenlin/a2f42d3c4378ed7b83de65c7a2222eb2

**Comment by uGokalp** [comment]
@yuchenlin  We are using the huggingface implementation of Roberta, Bert, Xlnet. From my understanding, the implementation of transformers Roberta is not an exact match of fairseq Roberta. The model Roberta was developed by Facebook so it makes sense that fairseq Roberta is functioning better.

[huggingface/transformers](https://github.com/huggingface/transformers)
