### ISSUE TITLE
Support language selection (For example, Russian).

### ISSUE THREAD

**Issue by svk-man** [EricFillion/happy-transformer#121]
Hello from Russia! Can you add language selection support? Accordingly, Russian. I have the task of predicting the next word from an available list of words. Or, if there is, how can I use it?

**Comment by svk-man** [comment]
Example
My sentence: Мой кот ... (My cat ...)
3 word is ест (eat)
List of possible words: ест (eat), поглощает (absorb), глотает (swallow), кушают (eats) etc.
I need to determine the probabilities of each word from the given list in the context of the phrase and make the most correct sentence.
Output: Мой кот ест (My cat eat).

**Comment by adamfillion** [comment]
Hi @svk-man , I am taking a look at this

**Comment by svk-man** [comment]
Hi @adamfillion , I hope it will help you:
https://github.com/vlomme/Russian-gpt-2
https://github.com/vlarine/transformers-ru

**Comment by adamfillion** [comment]
@svk-man  A pull request is open that will handle multi-lingual support.

For now, if you use model = HappyBERT(''bert-base-multilingual-cased") then you should be able to do masked word prediction with the language of your choice (question answering may not work as intended).

**Comment by EricFillion** [comment]
Added in #195. Now you can use any model available on Hugging Face's model distribution network for text classification, word prediction, next sentence prediction, question answering and token classification. 

New release coming soon.

**Comment by EricFillion** [comment]
It's now available in version 2.1.0 that's published to PyPi.
