### ISSUE TITLE
Any plans on other recent models like ALBERT?

### ISSUE THREAD

**Issue by yuchenlin** [EricFillion/happy-transformer#124]
Hi Eric,

Thanks for your wonderful work! I was wondering you would like to integrate some other recent models like ALBERT in the near future. That would make the experiments using happy-transformer more comprehensive!

**Comment by EricFillion** [comment]
HI Yuchen,

Our next round of development will occur in late April. We'll definitely look into implementing ALBERT.

**Comment by yuchenlin** [comment]
Thanks so much! Looking forward to it!
