### ISSUE TITLE
How can we save/load the fine-tuned MWP models?

### ISSUE THREAD

**Issue by yuchenlin** [EricFillion/happy-transformer#126]
Thanks!

**Comment by EricFillion** [comment]
Good question. Try using the pickle library to save and reload the HappyTransformer object

**Comment by uGokalp** [comment]
The underlying model is still a PyTorch model. You can save and load it as you would any PyTorch model.
You do need to check the correct attribute though.

**Comment by yuchenlin** [comment]
yes, thanks! got it! I will have a try and get back to you and put a snippet here for people to use in the future.
