### ISSUE TITLE
mask_lm_labels should be -100 instead of -1?

### ISSUE THREAD

**Issue by yuchenlin** [EricFillion/happy-transformer#128]
Hi,

We were running the fine-tuning mwp examples and found it reported a bug saying "Target -1 is out of bound". After debugging, we find that the doc of BertForMaskedLM says 

> masked_lm_labels (:obj:`torch.LongTensor` of shape :obj:`(batch_size, sequence_length)`, `optional`, defaults to :obj:`None`):
            Labels for computing the masked language modeling loss.
            Indices should be in ``[-100, 0, ..., config.vocab_size]`` (see ``input_ids`` docstring)
            Tokens with indices set to ``-100`` are ignored (masked), the loss is only computed for the tokens with labels

Thus, we modified the `mask_tokens` function by `labels[~masked_indices] = -100  # We only compute loss on masked tokens`. And it works now. Not sure if it is correct, could you please do a double check ?

**Comment by EricFillion** [comment]
Nice catch! We have fixed the problem
