### ISSUE TITLE
lr always 0 when fine-tuning mlm

### ISSUE THREAD

**Issue by yuchenlin** [EricFillion/happy-transformer#129]
Hi, 

I found that the fine-tuned model did not do better on the mwp on the trained corpus, so I debug the code by showing its learning rater as follows in the `train` function.

```python
  if global_step % logging_steps == 0:
                # tb_writer.add_scalar("lr", scheduler.get_lr()[0], global_step)
                print()
                print("\t lr:", scheduler.get_lr()[0])
                print("\t avg loss:", (tr_loss - logging_loss) / logging_steps, global_step)
                logging_loss = tr_loss
```

However, I found that `lr` is always 0..

**Comment by uGokalp** [comment]
Thank you for bringing this to my attention. 
We are working on a new release on the fine-tuning component.

**Comment by EricFillion** [comment]
By implementing your previous suggestions, we were able to fix this issue. Thank you once again for your help!
