### ISSUE TITLE
Predict multiple masked words

### ISSUE THREAD

**Issue by vanh17** [EricFillion/happy-transformer#131]
Is there a way to predict multiple masked words for this? So for example if I have a sentence:
```
"[MASK] have a [MASK] dog and I love [MASK] so much"
```
Thank you so much!

**Comment by EricFillion** [comment]
Great suggestion! 

We will look into adding this feature in the future.

**Comment by ted537** [comment]
Perhaps a function, `predict_mask` could be transformed into `predict_masks` or something similar, and then `predict_mask` could be left as a small method like so:

```
def predict_mask(our_params):
    return self.predict_masks(our_params)[0]
```

This would add support for predicting multiple MASK tokens while maintaining backwards compatibility
