### ISSUE TITLE
Any plan on adding HappyTransformer-XL soon?

### ISSUE THREAD

**Issue by vr25** [EricFillion/happy-transformer#133]

**Comment by EricFillion** [comment]
Hi Vipula!

I'm currently preoccupied with another project, but within the next month or so I will begin focusing on Happy Transformer. I'll for sure look into implementing Transformer-Xl into Happy Transformer when the time comes

**Comment by vr25** [comment]
Alright, thank you for your response and I am looking forward to the updates, thanks!

**Comment by ted537** [comment]
Which application are you looking to use Transformer XL for? Would it be sequence classification?

**Comment by vr25** [comment]
Yes, mostly text classificaion.

**Comment by EricFillion** [comment]
Added in #195. Now you can use any model available on Hugging Face's model distribution network for text classification, word prediction, next sentence prediction, question answering and token classification. 

New release coming soon.

**Comment by EricFillion** [comment]
It's now available in version 2.1.0 that's published to PyPi.
