### ISSUE TITLE
xlnet-base_uncased

### ISSUE THREAD

**Issue by vanh17** [EricFillion/happy-transformer#136]
Hi guys,

Thank you so much for putting up these transformers that make people happier. The thing is that the package is lacking one small part but quite important model of XLNet. I was wondering how hard it is to have a xlnet-base-uncased model included with the happy transformer. It can help with some tasks when uncased language models are preferred. I am also happy to participate in this process, just let me know how. Thanks

Best,

**Comment by ted537** [comment]
Under further consideration, this isn't really a responsibility of the Happy Transformer library. Models are loaded through hugging face, and a custom path can be supplied instead of a pretrained model.
