### ISSUE TITLE
ValueError: Number of processes must be at least 1

### ISSUE THREAD

**Issue by anandsubbu007** [EricFillion/happy-transformer#137]
I'm a beginner, help me with this.
When i try to train in colab it shows :
ValueError: Number of processes must be at least 1

**Comment by EricFillion** [comment]
Hi @anandsubbu007, it's hard for me to help without seeing your code. Can you please post your code here? If it is confidential, you can email it to happytransformer@gmail.com

**Comment by anandsubbu007** [comment]
I used the same code that is referred from the documentation:

![image](https://user-images.githubusercontent.com/55450843/89151190-01bd4c00-d57e-11ea-9402-b303aeee4a96.png)

![image](https://user-images.githubusercontent.com/55450843/89151164-efdba900-d57d-11ea-9d5f-17d525b36e8e.png)

**Comment by EricFillion** [comment]
Thanks @anandsubbu007 ,

Ted will help you from here.

**Comment by ted537** [comment]
https://github.com/EricFillion/happy-transformer/blob/13fbdad7834c776730cd7501a473e40b598f1b45/happytransformer/classifier_utils.py#L222

Looks like we were creating a pool with `process_count=0`. Should be a simple fix.

**Comment by ted537** [comment]
Also this code
```
text = [
        'Hi Anand, how are you',
        'Hi anand, did you complete',
        'Hi anand, did you complete your task',
        'Hi anand, what is status of task']

df = pd.DataFrame(text)
df.to_csv('train.csv',header=False)
pd.read_csv('train.csv')
```
Results in this output.
```
0,"Hi Anand, how are you"
1,"Hi anand, did you complete"
2,"Hi anand, did you complete your task"
3,"Hi anand, what is status of task"
```
From the HappyTransformer documentation, the label of each classifier must be `0` or `1`. Values of `2` and `3` are not acceptable.

**Comment by anandsubbu007** [comment]
Ok, thanks for your reply.
