### ISSUE TITLE
Add HappyTokenClassification

### ISSUE THREAD

**Issue by EricFillion** [EricFillion/happy-transformer#193]
Add functionality to run token classification models. No fine-tuning is required for the first iteration. 

- Create a class called HappyTokenClassification that has the same structure as HappyWordPrediction. 
- Add a public method called "classify_token" within HappyTokenClassification that takes in a string and returns a dataclass object with relevant information.
- Create test cases under tests/test_token_classification.py

Extra: 
- Add readme example under examples/token_classification/readme_examples.py
- Update readme. 

Useful link: https://huggingface.co/transformers/main_classes/pipelines.html#transformers.TokenClassificationPipeline

**Comment by ted537** [comment]
Giving that huggingface [describes](https://huggingface.co/transformers/v3.0.2/main_classes/pipelines.html#transformers.TokenClassificationPipeline) the `TokenClassificationPipeline` as "Named Entity Recognition pipeline using ModelForTokenClassification head.", could we consider calling this class `HappyNamedEntityRecognition`?

**Comment by EricFillion** [comment]
> Giving that huggingface [describes](https://huggingface.co/transformers/v3.0.2/main_classes/pipelines.html#transformers.TokenClassificationPipeline) the `TokenClassificationPipeline` as "Named Entity Recognition pipeline using ModelForTokenClassification head.", could we consider calling this class `HappyNamedEntityRecognition`?

Good idea. "Named Entity Recognition" is the standard way to describe what we want to do. However,   HappyNamedEntityRecognition may be too long. What's your opinion on "HappyNER"

**Comment by ted537** [comment]
I would propose "HappyEntityRecognition" as an alternative but its your call

**Comment by EricFillion** [comment]
Added in #195
