### ISSUE TITLE
Is it possible to get probability of specific word?

### ISSUE THREAD

**Issue by orenschonlab** [EricFillion/happy-transformer#196]
My aim is to have something like this:
```
from happytransformer import HappyWordPrediction
#--------------------------------------#
    happy_wp = HappyWordPrediction()  # default uses distilbert-base-uncased
    result = happy_wp.predict_probability("I think therefore I [am]")
    print(result[0].score) # 0.10172
    result = happy_wp.predict_probability("I think therefore I [went]")
    print(result[0].score) # 0.0001 - or something much lower the 0.10172

```
Is this possible?

**Comment by ted537** [comment]
When you say "probability of a specific word", do you want the probability when ALL words are considered?

**Comment by EricFillion** [comment]
Yes it is possible. Below is some code that you can use to achieve this. 

```
   results = happy_wp.predict_mask("I think therefore I [MASK]", targets =["a", "went"])
   for result in results:
        print(result.token, result.score)
```
prints: 
went 0.00024100413429550827
a 0.00010388820373918861

Let us know if you need help with anything else! We're always happy to help.

**Comment by orenschonlab** [comment]
@EricFillion Amazing thanks!
Theoretically, if `targets` are all the words in the English Language - 
The sum of all `result.score` over all the words is 1?

**Comment by EricFillion** [comment]
1. That's a good way to think of it. It also includes symbols, like questions marks and periods. 
2. Hmmm, I just ran the code in a fresh Google Colab environment and it worked fine. Can you please try again? 

@orenschonlab

**Comment by orenschonlab** [comment]
1. Is there a convinient way to get the rank of the target token probability from all the possible tokens in the language?

2. After building a fresh enviroment, I get the error:
`OSError: Unable to load weights from pytorch checkpoint file for 'distilbert-base-uncased' `
I don't get it for the other models - only for `'distilbert-base-uncased'`  (the others works fine)

**Comment by EricFillion** [comment]
1. When using predict_mask(), if you set targets to None (it's default value), then all tokens will be considered. You can then set the top_k parameter to a large value to to consider a vast amount of tokens. 
2.   Thanks for pointing this out. I Googled the error code and it seems like some people were able to solve it by adjusting their torch version. Others solved it by setting "force_download" to true when using Hugging Face's ".from_pretrained()" method. We'll consider adding "force_download" as an optional parameter for the next release.

**Comment by ted537** [comment]
```
def probability_of_token(happy_word_predictor,sentence,word):
    return happy_word_predictor.predict_mask(sentence,targets=[word])[0].score
```

**Comment by orko19** [comment]
@EricFillion Is it possible to get the rank of specific word?
For example:
```
   results = happy_wp.predict_mask("I think therefore I [MASK]", targets =["a", "went"])
   for result in results:
        print(result.token, result.score , result.rank)
```
When rank 0 is the token with the highest probability, etc

**Comment by EricFillion** [comment]
> @EricFillion Is it possible to get the rank of specific word?
> For example:
> 
> ```
>    results = happy_wp.predict_mask("I think therefore I [MASK]", targets =["a", "went"])
>    for result in results:
>         print(result.token, result.score , result.rank)
> ```
> 
> When rank 0 is the token with the highest probability, etc

Use enumerate. 
```
   results = happy_wp.predict_mask("I think therefore I [MASK]", targets =["a", "went"])
   for rank, result in enumerate(results):
        print(result.token, result.score, rank)
```
