### ISSUE TITLE
Generate full text 

### ISSUE THREAD

**Issue by ivan-bulka** [EricFillion/happy-transformer#238]
Hey, 
thank you for the great library.

I have an issue. 
I use happytransformers to generate emails. Fine-tuned a model and it generates data. But emails are not full. I mean that we generate a part of the email. 
Does exist a way to generate a full text? 

For example: 
Might need to specify a separator to differentiate emails in the text file? So the algorithm understands the difference between emails in the same file. 

Appreciate any advice in this task
Thanks

**Comment by ted537** [comment]
Could you provide a snippet of the text file you are using for training? Additionally, could you show examples of the output you are getting vs the output you desire?

**Comment by ivan-bulka** [comment]
Sure, 
It's examples of inputs: 
https://drive.google.com/file/d/1vx5Pl2iDt4rBT5kD5xLcxM5Htlg_84oc/view?usp=sharing (this file consist of 3k full emails)

It's examples of outputs we got: https://docs.google.com/document/d/1goHCH1rHuG1OPPBsUXifp3__4-inxFuRziSV5zkyqGQ/edit#heading=h.79rfftiy88z6 
As you see, we do not generate full emails and sometimes stop the generation in the middle of the sentence 

Desired output is a full email as in the file (https://drive.google.com/file/d/1vx5Pl2iDt4rBT5kD5xLcxM5Htlg_84oc/view?usp=sharing)

thanks

**Comment by ted537** [comment]
Which Happy Transformer methods are you using for training?

**Comment by ivan-bulka** [comment]
I use `HappyGeneration.train()`
It's a full code to train a model for the better understanding: https://colab.research.google.com/drive/1LIn2rEfeOF73TZZhTUz1-4FMuqA8QAfZ?authuser=1#scrollTo=kYHxw55M_I9j

**Comment by EricFillion** [comment]
Hi Ivan, 

I'm glad you enjoy the library! First off, try creating a GENSetting object and increase its max_length parameter.  Provide it to the generate_text() function you call from your model_1 object. For more details visit this [source](https://happytransformer.com/text-generation/settings/). 

If you wish to differentiate your training cases then you could try adding the text "<|endoftext|>" in-between your training cases
