### ISSUE TITLE
 ImportError: cannot import name 'WPTrainingArgs' from 'happy transformer'

### ISSUE THREAD

**Issue by Reijarmo** [EricFillion/happy-transformer#239]
Hello sorry for being new to this and to bother you with my problem,

I get the following error: ImportError: cannot import name 'WPTrainingArgs' from 'happy transformer' (/usr/local/lib/python3.7/dist-packages/happytransformer/init.py). 

Happy word prediction has no problem at all, only training does not work. Any tips how to solve the problem?  

Specs:
 Debian 8.3.06 
 Python  3.7.3
Installed with pip v 18.1

**Comment by EricFillion** [comment]
It seems like a typo. It should be "WPTrainArgs" not "WPTrainingArgs"
