### ISSUE TITLE
List of words/phrases that are not allowed to be generated 

### ISSUE THREAD

**Issue by EricFillion** [EricFillion/happy-transformer#246]
Allow the user to input a list of words/symbols/phrases when calling the generate_text() method available in both HappyGeneration and HappyTextToText. 

Hugging Face's bad_words_ids id parameter will help us accomplish this. However, it requires a list of tokens IDs that does not conform to Happy Transformer's goal to abstract the use of tokenizers and other lower levels components. So, the user will input a list of strings that will be converted to token IDs and passed to the bad_words_ids parameter.

**Comment by ted537** [comment]
Would we be trying to cover multi-token words with this feature?

**Comment by EricFillion** [comment]
The bad_words_ids ids parameter requires a list of lists where each index in the sublist is the ID of a the token in the form of an int. Then, the model prevents any combinations of the sublists. For example, if bad_word_ids is [[0], [1, 2]]. Then, the ID 0 will never be allowed. The IDs 1 and 2 will be allowed so long that 1 does proceed 2.  

So, yes we will cover multi-token words and we will even support phrases. The user will provide a list of strings and we will convert each string into its IDs.

**Comment by ted537** [comment]
Excellent! Sounds like implementing this for Happy Transformer should be pretty straightforward then.

**Comment by ujwal-narayan** [comment]
Hi,
Love the library, and would love to contribute to it, so if this is not done yet, can I pick it up?

**Comment by EricFillion** [comment]
> Hi,
> Love the library, and would love to contribute to it, so if this is not done yet, can I pick it up?

For sure! Feel free to fork the library and add this feature. Then, make a PR when it's ready.
