### ISSUE TITLE
[Question] : How to train multi-label text classification model ?

### ISSUE THREAD

**Issue by VinayChaudhari1996** [EricFillion/happy-transformer#247]
Hello Guys , 

I have text dataset having 3 columns. 
Col A : News article
Col B : 4 unique classes (value count) 
Col C : 118 unique classes (value count)

How can I train multi-label model on my custom dataset ?

Thanks

**Comment by EricFillion** [comment]
Hi!

I suggest you check out this article to learn more about fine-tuning a text classification model. You can also visit this example under Happy Transformer's examples folder for a multi-class example. 

Training a multi-class model is essentially the same as training a binary text classification model. Just don't forget to set the _num_labels_ parameter when instantiating a HappyTextClassification object. Then, you can use the labels "0," "1," "2" etc within your training csv. 

As for your specific use case, I recommend that you use a single model to classify your text into column B and then another for column C. However, 118 classes is a lot so you may want combine them. 


article: https://www.vennify.ai/train-text-classification-transformers/

multi-class example: https://github.com/EricFillion/happy-transformer/blob/master/examples/text_classification/training_example.py

**Comment by EricFillion** [comment]
Be sure to join the Happy Transformer Discord server if you have any further questions. 

https://discord.gg/psVwe3wfTb
