### ISSUE TITLE
HappyTextClassification : Target -1 is out of bounds.  

### ISSUE THREAD

**Issue by olwethumlimi** [EricFillion/happy-transformer#248]
csv labels
  text
  value
size=14000

return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index) IndexError: 
Target -1 is out of bounds.

**Comment by EricFillion** [comment]
Hi, 

The lowest valid label number is "0." 

Thanks for bringing this up and I'll make it more clear within the documentation.
