### ISSUE TITLE
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by kingafy** [EricFillion/happy-transformer#249]
I was trying the text generation pipeline. I downloaded the GPT neo file in my local directory and executing the below code:
from happytransformer import HappyGeneration

#happy_gen = HappyGeneration("GPT-NEO", "https://huggingface.co/EleutherAI/gpt-neo-1.3B")
happy_gen = HappyGeneration(model_name="GPT-NEO",load_path=<my local folder having the model EleutherAI/gpt-neo-1.3B)

from happytransformer import GENSettings
beam_settings = GENSettings(num_beams=5, max_length=50, no_repeat_ngram_size=3)

top_p_settings = GENSettings(do_sample=True, top_k=0, top_p=0.5, max_length=50)

question = "What is a dog?" 
result = happy_gen.generate_text(question, args=beam_settings) 
print(result.text)

but I am getting error:-

Traceback (most recent call last):
  File "path\envs\torch_cpu1\lib\site-packages\transformers\modeling_utils.py", line 1063, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "path\envs\torch_cpu1\lib\site-packages\torch\serialization.py", line 577, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "path\envs\torch_cpu1\lib\site-packages\torch\serialization.py", line 241, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_knowledge.py", line 11, in <module>
    happy_gen = HappyGeneration(model_name="GPT-NEO",load_path=r"path\gpt-neo-1.3B")
  File "path\happytransformer\happy_generation.py", line 50, in __init__
    model = AutoModelForCausalLM.from_pretrained(load_path)
  File "path\envs\torch_cpu1\lib\site-packages\transformers\models\auto\auto_factory.py", line 360, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **kwargs
  File "C:\Users\anshuman.a.mahapatra\Anaconda3\envs\torch_cpu1\lib\site-packages\transformers\modeling_utils.py", line 1066, in from_pretrained
    f"Unable to load weights from pytorch checkpoint file for '{pretrained_model_name_or_path}' "
OSError: Unable to load weights from pytorch checkpoint file for 'local_path\gpt-neo-1.3B' at 'local_path\gpt-neo-1.3B\pytorch_model.bin'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by EricFillion** [comment]
I recommend you use the following command to download/use gpt-neo-1.3B. 
`
happy_gen = HappyGeneration("GPT-NEO", "EleutherAI/gpt-neo-1.3B") 
` 
There are several different files that are required to be within your load folder for it to load properly. You can call happy_gen.save("save-path/") to save the model and all of the required files after you loaded the model with the command above. Then, you can load it the same way you attempted.
