### ISSUE TITLE
Issue while loading the model using load_path argument

### ISSUE THREAD

**Issue by siddhantsambit** [EricFillion/happy-transformer#252]
While saving the model using save method it is getting saved in the desired path provided in the argument but while loading the model it is always displaying the model_type and name as distillbert even though while saving the model type is different.

**Comment by EricFillion** [comment]
This can be resolved by updating the model_name and model_type parameters when load_path is not a blank string. As of right now, the proper model and tokenizer are loaded when load_path is provided so it does not impact performance. But, we should update the model_name and model_type parameters to avoid confusion. 

I suggest we update model_name and tokenizer_name  to "LOADED_MODEL" and "LOADED_TOKENIZER" respectively when load_path is provided

**Comment by EricFillion** [comment]
@MandilKarki

**Comment by MandilKarki** [comment]
affirmative.

**Comment by EricFillion** [comment]
Version three contains new code for loading models. You no longer need to provide both _model_name_ and _load_path_ when loading a saved model. You now only need to provide the path to  _model_name_ that you used for saving the model.   

```
from happytransformer import HappyGeneration

happy_gen_1 = HappyGeneration(model_type="GPT-NEO", model_name="EleutherAI/gpt-neo-125M")
happy_gen._1.save(model/")

happy_gen_2= HappyGeneration(model_type="GPT-NEO", model_name="model/")
```
