### ISSUE TITLE
Training gpt with line by line

### ISSUE THREAD

**Issue by zaharPonimash** [EricFillion/happy-transformer#275]
How can I train gpt-neo with line_by_line parameter?

**Comment by EricFillion** [comment]
If you have a Nvidia GPU set up properly then Happy Transformer should automatically connect to it. You can run this code below and it doesn't print "cuda" then there is a problem with your setup. 

`    
import torch    
device = torch.device(
            "cuda" if torch.cuda.is_available()
            else "cpu"
        )
print(device)
`
We on't support line_by_line training for text generation. For gpt-neo however, you can add the text "<|endoftext|>"  to your training file which will be converted into a token to specify the end of a standalone piece of text

**Comment by EricFillion** [comment]
If you have a Nvidia GPU set up properly then Happy Transformer should automatically connect to it. You can run this code below and it doesn't print "cuda" then there is a problem with your setup. 


```
import torch    
device = torch.device(
            "cuda" if torch.cuda.is_available()
            else "cpu"  )
print(device)
```
We don't support line_by_line training for text generation. For gpt-neo however, you can add the text "<|endoftext|>"  to your training file which will be converted into a token to specify the end of a standalone piece of text.

**Comment by zaharPonimash** [comment]
Thank you very much for your reply!
