### ISSUE TITLE
HappyTextToText hunging and fails

### ISSUE THREAD

**Issue by socaseinpoint** [EricFillion/happy-transformer#276]
I'm trying to execute HappyTextToText. It's hanging and then failed with the following logs, if I execute after it fails one more time it starts working as expected. 

`
12/03/2021 09:50:40 PM INFO: Running cell:
happy_tt  = HappyTextToText("MARIAN", "Helsinki-NLP/opus-mt-kl-en")

12/03/2021 09:51:53 PM INFO: Cell returned
Traceback (most recent call last):
  File "/usr/local/bin/runipy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/runipy/main.py", line 158, in main
    nb_runner.run_notebook(skip_exceptions=args.skip_exceptions)
  File "/usr/local/lib/python3.8/dist-packages/runipy/notebook_runner.py", line 232, in run_notebook
    self.run_cell(cell)
  File "/usr/local/lib/python3.8/dist-packages/runipy/notebook_runner.py", line 207, in run_cell
    raise NotImplementedError(
NotImplementedError: unhandled iopub message: comm_open
The terminal process "/bin/bash '-c', 'docker run --rm -it  -p 3000:3000/tcp translator-demo-repo2:latest'" terminated with exit code: 1.
`

I have set up environment in docker:

FROM ubuntu:latest
WORKDIR /app
RUN apt update
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update -y
RUN apt install python3-pip -y
RUN python3 -m pip install --user --upgrade pip
RUN pip3 install torch torchvision --no-cache-dir
RUN pip install runipy
RUN pip install happytransformer --no-cache-dir
RUN pip install ipywidgets
RUN jupyter nbextension enable --py widgetsnbextension

**Comment by EricFillion** [comment]
It looks like runipy is calling an error. This package doesn't appear to be maintained anymore.
