### ISSUE TITLE
Too much time to eval&train

### ISSUE THREAD

**Issue by saloyiana** [EricFillion/happy-transformer#277]
I am trying to fine tune the mt5 model for grammatical error correction task using happy-transformers, and following the provided tutorial. However, it takes too much time ( approximately 12 hours !) to output the result of ( eval function ) even before stating the training ! 

Did anyone face the same ? 

Note: evaluation dataset contains approximately “1000 “ pairs of strings [ input, target ].

**Comment by ted537** [comment]
Which tutorial is this? Do you have a link?

**Comment by EricFillion** [comment]
See #319.
