### ISSUE TITLE
Error while fine tuning GPT-J

### ISSUE THREAD

**Issue by sallumandya1995** [EricFillion/happy-transformer#287]
For research, i am facing problem when i am fine tuning GPTJ and flax-community/gpt-neo-125M-code-clippy transformer
weights . I am getting error 
RuntimeError: CUDA out of memory. Tried to allocate 1.88 GiB (GPU 0; 39.59 GiB total capacity; 
36.94 GiB already allocated; 638.19 MiB free; 36.98 GiB reserved in total by PyTorch).

I have one VM with 2 TPUs and another with A100 and i am getting same error mentioned above .
Appreciate if you could  help me with sorting out the errors which i mentioned.

**Comment by EricFillion** [comment]
You can now fine-tune GPT-J with version 3.0.0 by leveraging the new DeepSpeed functionality. I recommend you rent an 8xA6000 instance or something similar. 

First install DeepSpeed.

```
DS_BUILD_UTILS=1 pip install deepspeed
```

Then provide "ZERO-2" to GENTrainArgs's deepspeed parameter. 

```
train_args = GENTrainArgs(deepspeed="ZERO-2")
```

Finally, ensure your training code is within a script and call it with the  _deepspeed_ command. 

```
deepspeed train.py
```
