### ISSUE TITLE
Multi-GPU version

### ISSUE THREAD

**Issue by Sukii** [EricFillion/happy-transformer#289]
Is there a way to add support for load distribution to multiple GPUs using Accelerate API?

**Comment by ted537** [comment]
What's Acclerate API? Could you link to it?

**Comment by Sukii** [comment]
https://github.com/huggingface/accelerate

**Comment by EricFillion** [comment]
Happy Transformer does not currently support Accelerate. It would be a large task to add it. Thanks for the question though, I'm sure others have also wondered this.
