### ISSUE TITLE
HI, sorry but your grammar model is very weak on real cases

### ISSUE THREAD

**Issue by caprone** [EricFillion/happy-transformer#293]
HI
I tested on some simple sentences, like:

args = TTSettings(num_beams=5, min_length=1, max_length=5000)
happy_grammar = HappyTextToText("T5", "vennify/t5-base-grammar-correction")
result = happy_grammar.generate_text('This mvie did everUthing a van dqmme mLvie shoHld do Ahich is martial arts and action', args=args)

your model result : " 'This mvie did everthing a van dqmme mLvie shoHld do, which is martial arts and action.'

what's your grammar model purpose????? is it a joke?....mah....

**Comment by Sukii** [comment]
Please run the output "This mvie did everthing a van dqmme mLvie shoHld do, which is martial arts and action" as input gain to see if it progressively fixes it. Just a suggestion (not tested). Yes, serious stuff usually start off like a joke!

**Comment by caprone** [comment]
HI and thanks for your help..
yes, some gain but very negligible...
But I found that the simple Spellcheker library, that use Levenshtein distance and a base statistic, works great on misspelling...probably this  transofmers based grammar, works mainly good only on grammatical errors,
I tried also "contextualSpellCheck" package, based on Spacy, and it works even worse on mispelling and also on grammar than this "grammar corrector"..
then, for the moment, I found a good solution a --pipe-- of:  cleaning,  spellcheker,  grammar...

**Comment by Sukii** [comment]
Looks more like QWERTY keyboard spelling mistake. Probably we need a QWERTY-distance based rather than Levenshtein distance based **spellcheck**

**Comment by caprone** [comment]
HI, not...is only random noise add to text :)

**Comment by ted537** [comment]
Since Transformer models look at things on a token-by-token basis (1 token ~= 1 word for common words), we don't expect them to be good at this task (mis-spelled words)
