### ISSUE TITLE
Sharing models to HuggingFace Hub

### ISSUE THREAD

**Issue by kwen1510** [EricFillion/happy-transformer#301]
Hi,

Thanks so much for the happy-transformer! It is a game-changer!

Can I check how I can push/share my model to the hugging face hub after training?

Thank you!

**Comment by EricFillion** [comment]
Hello! 

You'll want to save the model by calling ".save("file-path/)" and then you can upload the files in the same way that you would do if they were saved from Hugging Face's transformers library. 

Here's an article I published on the topic. 

https://www.vennify.ai/upload-happy-transformer/

**Comment by kwen1510** [comment]
Thank you very much! It's been helpful!
