### ISSUE TITLE
I created a train.csv and I get an error about 

### ISSUE THREAD

**Issue by thistleknot** [EricFillion/happy-transformer#307]
![image](https://user-images.githubusercontent.com/5154106/207501110-553bee2e-059a-4637-b3f3-c48d70e22948.png)
newqa_df.to_csv('train.csv')
![image](https://user-images.githubusercontent.com/5154106/207501273-477dd488-2b67-4376-978b-d2a30a0a34e2.png)

happytransformer documentation says I shouldn't have that field/column
* https://happytransformer.com/question-answering/finetuning/
* 
I'll either get an error about having or missing 'answer_end'

**Comment by EricFillion** [comment]
Thanks for pointing this out. I believe the code from [ QATrainer.__add_end_idx() ](https://github.com/EricFillion/happy-transformer/blob/028cfa44a705013b2783f43ff1e8a7f018191902/happytransformer/qa/trainer.py#L158) method is causing the issue. The final else statement did not add a _answer_end_ key  to the _answers_ list. I've applied a [temporary fix ](https://github.com/EricFillion/happy-transformer/blob/ecd15f1b18e64ac36cdf4241c0d563e40ef170b7/happytransformer/qa/trainer.py#L157)within the _ef/qa-end-index_ branch. 

Please let me know if this solves your issue. Here's a command for you to install a new version of Happy Transformer with the fix applied. 

`pip install --upgrade git+https://github.com/EricFillion/happy-transformer.git@ecd15f1b18e64ac36cdf4241c0d563e40ef170b7`

**Comment by thistleknot** [comment]
I was thinking why doesn't the answer have an end?  It makes sense, I've
seen it in other q a answer sets.  It would help me where I'm cosine
similarity merging two answers together which both have their own min's and
max's (which I was hoping to wrap around), but hey, I don't want to really
suggest anything, I just want it to work. I presume it's going to read the
rest of the text after the answer_start.

**Comment by thistleknot** [comment]
I think I realized what my error was.  My CSV was malformed.  Had a whole paragraph in there with comma's.  I see it works with the train_eval.csv you have.  My apologies.

**Comment by ted537** [comment]
Having a check that CSV columns are consistent could be useful to provide a more obvious error message for this kind of situation.

**Comment by thistleknot** [comment]
I've been struggling with trying to train a model.  I followed your
methods.  They work as described.  But what I'm trying to do now is mimic
the run_qa.py examples they have for bloomz and gpt-neo

https://huggingface.co/bigscience/mt0-small
import sagemaker
import boto3
from sagemaker.huggingface import HuggingFace

# gets role for executing training job
iam_client = boto3.client('iam')
role =
iam_client.get_role(RoleName='{IAM_ROLE_WITH_SAGEMAKER_PERMISSIONS}')['Role']['Arn']
hyperparameters = {
'model_name_or_path':'bigscience/mt0-small',
'output_dir':'/opt/ml/model'
# add your remaining hyperparameters
# more info here
https://github.com/huggingface/transformers/tree/v4.17.0/examples/pytorch/question-answering
}

# git configuration to download our fine-tuning script
git_config = {'repo':
'https://github.com/huggingface/transformers.git','branch':
'v4.17.0'}

# creates Hugging Face estimator
huggingface_estimator = HuggingFace(
entry_point='run_qa.py',
source_dir='./examples/pytorch/question-answering',
instance_type='ml.p3.2xlarge',
instance_count=1,
role=role,
git_config=git_config,
transformers_version='4.17.0',
pytorch_version='1.10.2',
py_version='py38',
hyperparameters = hyperparameters
)

# starting the train job
huggingface_estimator.fit()

Here is one for

GPT-Neo

import sagemakerimport boto3from sagemaker.huggingface import HuggingFace
# gets role for executing training job
iam_client = boto3.client('iam')
role = iam_client.get_role(RoleName='{IAM_ROLE_WITH_SAGEMAKER_PERMISSIONS}')['Role']['Arn']
hyperparameters = {
	'model_name_or_path':'EleutherAI/gpt-neo-2.7B',
	'output_dir':'/opt/ml/model'
	# add your remaining hyperparameters
	# more info here
https://github.com/huggingface/transformers/tree/v4.17.0/examples/pytorch/question-answering
}
# git configuration to download our fine-tuning script
git_config = {'repo':
'https://github.com/huggingface/transformers.git','branch': 'v4.17.0'}
# creates Hugging Face estimator
huggingface_estimator = HuggingFace(
	entry_point='run_qa.py',
	source_dir='./examples/pytorch/question-answering',
	instance_type='ml.p3.2xlarge',
	instance_count=1,
	role=role,
	git_config=git_config,
	transformers_version='4.17.0',
	pytorch_version='1.10.2',
	py_version='py38',
	hyperparameters = hyperparameters
)
# starting the train job
huggingface_estimator.fit()


but I obviously don't want to jump through the sagemaker hoops (which
I did, but due to not specifying I wanted to download the model on the
first attempt, I used all my cycles :( )

so what I'm trying to do is get a GPT-Neo model fine-tuned on the
SQuad answer set.  Then have it process a prompt (say Plato's complete
works) that I can then ask a question of it.

But I'm not sure how I'm suppose to do that considering the example of
GPT-Neo in HappyTransformer doesn't have a QA training method.
