### ISSUE TITLE
How to get multiple labels as output and not just one using classify_text ?

### ISSUE THREAD

**Issue by mdnihal29** [EricFillion/happy-transformer#314]
Hi.. I would like to know how to combine two multi label text classification models and I just don't want one output but rather top 3 labels based on their score.

**Comment by ted537** [comment]
https://github.com/EricFillion/happy-transformer/blob/master/happytransformer/happy_text_classification.py

It's not supported right now, but should be simple to add.

In the meantime, you could set up the pipeline yourself (stabler, but slightly more work), or rip the pipeline off of your `HappyTextClassification` instance ( **could break at any time, so pin the HappyTransformer version if you do this. Not recommended for anything but quick-and-dirty experiment.** )

**Comment by mdnihal29** [comment]
okay, Thanks!
