### ISSUE TITLE
ValueError: Unrecognized configuration class <class 'transformers.models.t5.configuration_t5.T5Config'>

### ISSUE THREAD

**Issue by Rhitabrat** [EricFillion/happy-transformer#317]
I used this tutorial for my project - https://www.vennify.ai/fine-tune-grammar-correction/dsds

I saved the model providing just the path like this
`happy_tt.save("/model-1")`

When I load it, using this code
`happy_tt = HappyGeneration(load_path="/model-1")`

I get this error

```
ValueError: Unrecognized configuration class <class 'transformers.models.t5.configuration_t5.T5Config'> 
for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, 
BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CTRLConfig, 
Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTNeoConfig, GPTNeoXConfig, 
GPTNeoXJapaneseConfig, GPTJConfig, MarianConfig, MBartConfig, MegatronBertConfig, MvpConfig, OpenAIGPTConfig, 
OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, 
RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, Speech2Text2Config, TransfoXLConfig, 
TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig.
```

**Comment by ted537** [comment]
Hi, thanks for reaching out.  T5 is a text-to-text model, so `HappyTextToText` is the relevant class to use. It looks like you saved the model with `HappyTextToText`, but are then trying to load the model with `HappyGeneration`.

`HappyTextToText` and `HappyGeneration` use completely different model architecture (generative vs text-to-text which achieve similar goals (generates text 📖 ), but are incompatible.
