### ISSUE TITLE
Suggestion: it may better have trust_remote_code parameter in HappyTransformer class

### ISSUE THREAD

**Issue by lissa2077** [EricFillion/happy-transformer#320]
Here is the situation that I face: (please ignore the model name)
<img width="879" alt="image" src="https://user-images.githubusercontent.com/71573064/228564981-09bfa3df-630c-482f-b78f-999400419843.png">  
Maybe some users will face it problem in future? It is better to put a arg in [ __init__ ](https://github.com/EricFillion/happy-transformer/blob/028cfa44a705013b2783f43ff1e8a7f018191902/happytransformer/happy_transformer.py#L11) to store trust_remote_code(default False) then user can set it.  
```
def __init__(self, model_type, model_name, model, load_path="", use_auth_token: str = None):
    ...
    if load_path != "":
                self.tokenizer = AutoTokenizer.from_pretrained(load_path,trust_remote_code=trust_remote_code)
            else:
                self.tokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=use_auth_token,trust_remote_code=trust_remote_code)
```

**Comment by EricFillion** [comment]
This feature was added in version 3.0.0. You can now supply the parameter _trust_remote_code_ to all HappyTransformer child classes such as HappyGeneration. 

`
from happytransformer import HappyGeneration

happy_tg = HappyGeneration("MODEL-TYPE", "MODEL-NAME", trust_remote_code=True)

`
