### ISSUE TITLE
Are other languages compatible

### ISSUE THREAD

**Issue by avakado0** [EricFillion/happy-transformer#325]
Hey there, 

Thank you very much your effors into your code and educational materials. Is this library only relevant for English or can it be made use of by other languages too if necessary trainings are done?

**Comment by Sukii** [comment]
This is based on T5, so I suppose it can do other Latin-based languages,
but I think you can use mT5 (which is much bigger in size) for other
scripts. Also there is *byT5*, which is a unicode version, but again it is
bigger in size.
I have no idea if they are supported?

Suki

**Comment by EricFillion** [comment]
Hi,

You can load models for other languages. You can search for models on [hf.co ](https://huggingface.co/models)  by language and then plug them into a HappyTransformer class like HappyTextToText so long that the task is supported. 

You may also be interested in multilingual models like [mT5](https://huggingface.co/google/mt5-base).
